const BoardAI = (props) => {
  
    return(
      <div className='board' id="player-board">
        <div className='square empty' id="aisquare-1-1" ></div>
        <div className='square empty' id="aisquare-2-1" ></div>
        <div className='square empty' id="aisquare-3-1" ></div>
        <div className='square empty' id="aisquare-4-1" ></div>
        <div className='square empty' id="aisquare-5-1" ></div>
        <div className='square empty' id="aisquare-6-1" ></div>
        <div className='square empty' id="aisquare-7-1" ></div>
        <div className='square empty' id="aisquare-8-1" ></div>
        <div className='square empty' id="aisquare-9-1" ></div>
        <div className='square empty' id="aisquare-10-1" ></div>
        <div className='square empty' id="aisquare-1-1" ></div>
        <div className='square empty' id="aisquare-2-2" ></div>
        <div className='square empty' id="aisquare-3-2" ></div>
        <div className='square empty' id="aisquare-4-2" ></div>
        <div className='square empty' id="aisquare-5-2" ></div>
        <div className='square empty' id="aisquare-6-2" ></div>
        <div className='square empty' id="aisquare-7-2" ></div>
        <div className='square empty' id="aisquare-8-2" ></div>
        <div className='square empty' id="aisquare-9-2" ></div>
        <div className='square empty' id="aisquare-10-2" ></div>
        <div className='square empty' id="aisquare-1-3" ></div>
        <div className='square empty' id="aisquare-2-3" ></div>
        <div className='square empty' id="aisquare-3-3" ></div>
        <div className='square empty' id="aisquare-4-3" ></div>
        <div className='square empty' id="aisquare-5-3" ></div>
        <div className='square empty' id="aisquare-6-3" ></div>
        <div className='square empty' id="aisquare-7-3" ></div>
        <div className='square empty' id="aisquare-8-3" ></div>
        <div className='square empty' id="aisquare-9-3" ></div>
        <div className='square empty' id="aisquare-10-3" ></div>
        <div className='square empty' id="aisquare-1-4" ></div>
        <div className='square empty' id="aisquare-2-4" ></div>
        <div className='square empty' id="aisquare-3-4" ></div>
        <div className='square empty' id="aisquare-4-4" ></div>
        <div className='square empty' id="aisquare-5-4" ></div>
        <div className='square empty' id="aisquare-6-4" ></div>
        <div className='square empty' id="aisquare-7-4" ></div>
        <div className='square empty' id="aisquare-8-4" ></div>
        <div className='square empty' id="aisquare-9-4" ></div>
        <div className='square empty' id="aisquare-10-4" ></div>
        <div className='square empty' id="aisquare-1-5" ></div>
        <div className='square empty' id="aisquare-2-5" ></div>
        <div className='square empty' id="aisquare-3-5" ></div>
        <div className='square empty' id="aisquare-4-5" ></div>
        <div className='square empty' id="aisquare-5-5" ></div>
        <div className='square empty' id="aisquare-6-5" ></div>
        <div className='square empty' id="aisquare-7-5" ></div>
        <div className='square empty' id="aisquare-8-5" ></div>
        <div className='square empty' id="aisquare-9-5" ></div>
        <div className='square empty' id="aisquare-10-5" ></div>
        <div className='square empty' id="aisquare-1-6" ></div>
        <div className='square empty' id="aisquare-2-6" ></div>
        <div className='square empty' id="aisquare-3-6" ></div>
        <div className='square empty' id="aisquare-4-6" ></div>
        <div className='square empty' id="aisquare-5-6" ></div>
        <div className='square empty' id="aisquare-6-6" ></div>
        <div className='square empty' id="aisquare-7-6" ></div>
        <div className='square empty' id="aisquare-8-6" ></div>
        <div className='square empty' id="aisquare-9-6" ></div>
        <div className='square empty' id="aisquare-10-6" ></div>
        <div className='square empty' id="aisquare-1-7" ></div>
        <div className='square empty' id="aisquare-2-7" ></div>
        <div className='square empty' id="aisquare-3-7" ></div>
        <div className='square empty' id="aisquare-4-7" ></div>
        <div className='square empty' id="aisquare-5-7" ></div>
        <div className='square empty' id="aisquare-6-7" ></div>
        <div className='square empty' id="aisquare-7-7" ></div>
        <div className='square empty' id="aisquare-8-7" ></div>
        <div className='square empty' id="aisquare-9-7" ></div>
        <div className='square empty' id="aisquare-10-7" ></div>
        <div className='square empty' id="aisquare-1-8" ></div>
        <div className='square empty' id="aisquare-2-8" ></div>
        <div className='square empty' id="aisquare-3-8" ></div>
        <div className='square empty' id="aisquare-4-8" ></div>
        <div className='square empty' id="aisquare-5-8" ></div>
        <div className='square empty' id="aisquare-6-8" ></div>
        <div className='square empty' id="aisquare-7-8" ></div>
        <div className='square empty' id="aisquare-8-8" ></div>
        <div className='square empty' id="aisquare-9-8" ></div>
        <div className='square empty' id="aisquare-10-8" ></div>
        <div className='square empty' id="aisquare-1-9" ></div>
        <div className='square empty' id="aisquare-2-9" ></div>
        <div className='square empty' id="aisquare-3-9" ></div>
        <div className='square empty' id="aisquare-4-9" ></div>
        <div className='square empty' id="aisquare-5-9" ></div>
        <div className='square empty' id="aisquare-6-9" ></div>
        <div className='square empty' id="aisquare-7-9" ></div>
        <div className='square empty' id="aisquare-8-9" ></div>
        <div className='square empty' id="aisquare-9-9" ></div>
        <div className='square empty' id="aisquare-10-9" ></div>
        <div className='square empty' id="aisquare-1-10" ></div>
        <div className='square empty' id="aisquare-2-10" ></div>
        <div className='square empty' id="aisquare-3-10" ></div>
        <div className='square empty' id="aisquare-4-10" ></div>
        <div className='square empty' id="aisquare-5-10" ></div>
        <div className='square empty' id="aisquare-6-10" ></div>
        <div className='square empty' id="aisquare-7-10" ></div>
        <div className='square empty' id="aisquare-8-10" ></div>
        <div className='square empty' id="aisquare-9-10" ></div>
        <div className='square empty' id="aisquare-10-10" ></div>
      </div>
    )
  }

export default BoardAI